/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StationerySSDbysajid.rifat;

/**
 *
 * @author ASUS
 */
public class CheckoutProduct extends javax.swing.JPanel {

    /**
     * Creates new form CheckoutProduct
     */
    public CheckoutProduct(String n,float p,int q) {
        initComponents();
        name.setText(n);
        priceper.setText(String.valueOf(p));
        qty.setText(String.valueOf(q));
        money.setText(String.valueOf(p*q));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        priceper = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        qty = new javax.swing.JLabel();
        money = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        name.setBackground(new java.awt.Color(0, 0, 0));
        name.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        name.setText("jLabel1");

        priceper.setBackground(new java.awt.Color(255, 255, 0));
        priceper.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        priceper.setText("jLabel1");

        name2.setBackground(new java.awt.Color(255, 255, 0));
        name2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name2.setText("tk");

        name3.setBackground(new java.awt.Color(255, 255, 0));
        name3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name3.setText("X");

        qty.setBackground(new java.awt.Color(255, 255, 0));
        qty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qty.setText("jLabel1");

        money.setBackground(new java.awt.Color(255, 255, 0));
        money.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        money.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        money.setText("jLabel1");

        name4.setBackground(new java.awt.Color(255, 255, 0));
        name4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name4.setText("tk");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(priceper, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name2)
                        .addGap(18, 18, 18)
                        .addComponent(name3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(qty)
                        .addGap(46, 46, 46)
                        .addComponent(money, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(name4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(name)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceper)
                    .addComponent(name2)
                    .addComponent(name3)
                    .addComponent(qty)
                    .addComponent(money)
                    .addComponent(name4))
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel money;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel priceper;
    private javax.swing.JLabel qty;
    // End of variables declaration//GEN-END:variables
}
